name: "Validate and Build Project"
on: [push, pull_request]

permissions:
  contents: read

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  build_project:
    name: "Build Project"
    needs: validation  # Only run if validation succeeds
    runs-on: ubuntu-latest
    container: springci/spring-boot-ci:2.7.x  # Specify the Docker image to use
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: ./gradlew -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false --max-workers=4 --no-daemon build -x asciidoctorPdf -x asciidoctor

  upload_jars:
    name: "Upload Jars"
    needs: build_project  # Only run if build succeeds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Gradle (if not done in build_project.sh)
        run: ./gradlew build # Or your specific Gradle build command if needed
      - uses: actions/upload-artifact@v4
        with:
          name: "jars"
          path: "**/*.jar"
